# Generated by Django 3.0.3 on 2020-03-21 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=6)),
                ('course_description', models.CharField(max_length=200)),
                ('course_department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_name', models.CharField(max_length=50)),
                ('prof_deparment', models.CharField(max_length=50)),
                ('prof_research_interest', models.CharField(blank=True, max_length=50)),
                ('img_src', models.CharField(blank=True, default='', max_length=100)),
                ('website', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProfReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_review_own', models.CharField(blank=True, max_length=200)),
                ('prof_review_reiability', models.IntegerField(default=0)),
                ('anonymous', models.BooleanField(default=False)),
                ('prof_own', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.Professors')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof_urev', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_puntuality_own', models.IntegerField()),
                ('prof_grading_own', models.IntegerField()),
                ('prof_strictness_rating_own', models.IntegerField()),
                ('prof_teaching_skill_own', models.IntegerField()),
                ('prof_enthusiasm_own', models.IntegerField()),
                ('prof_overall_own', models.IntegerField()),
                ('prof_own', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof_r', to='rate.Professors')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof_urate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prof_to_subj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_of_subj', models.IntegerField(blank=True, null=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.Professors')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('user_photo', models.CharField(blank=True, max_length=50, null=True)),
                ('user_rating', models.IntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('block_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_review_own', models.CharField(blank=True, max_length=200)),
                ('course_review_reiability', models.IntegerField(default=0)),
                ('anonymous', models.BooleanField(default=False)),
                ('course_own', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.Courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_urev', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_difficulty_own', models.IntegerField()),
                ('course_workload_own', models.IntegerField()),
                ('course_content_rating_own', models.IntegerField()),
                ('course_own', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_r', to='rate.Courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_urate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
