# Generated by Django 3.0.3 on 2020-03-21 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('review_id', models.CharField(max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample1', to=settings.AUTH_USER_MODEL)),
                ('user_to_be_reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
