# Generated by Django 3.0.3 on 2020-03-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='review_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
