# Generated by Django 3.0.3 on 2020-03-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0004_comments_on_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments_on_review',
            name='user',
        ),
    ]
