# Generated by Django 3.0.3 on 2020-03-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0005_remove_comments_on_review_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments_on_review',
        ),
    ]
